version: "3.9"
services:
  composer:
    image: 'composer:2.1.12'
    volumes:
      - ./:/app
    working_dir: /app
    command: composer install --ignore-platform-reqs

  redis:
    image: "redis:6.2.6-alpine3.15"

  db:
    image: mariadb:10.6.5-focal
    ## Uncomment for MySQL SSL
    # command:
    # - "--require_secure_transport=ON"
    # - "--ssl-ca=/etc/certs/root-ca.pem"
    # - "--ssl-cert=/etc/certs/server-cert.pem"
    # - "--ssl-key=/etc/certs/server-key.pem"
    # volumes:
    #   # See https://techsparx.com/software-development/docker/damp/mysql-ssl-connection.html
    #   - type: bind
    #     source: ./certs
    #     target: /etc/certs/
    #   - ./.docker/db/custom_config:/etc/mysql/conf.d
    
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_DATABASE: db

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 8081:8080
    ## Uncomment for MySQL SSL
    # environment:
    #   DB_SSL_KEY: '/certs/client-key.pem'
    #   DB_SSL_CERT: '/certs/client-cert.pem'
    #   DB_SSL_CA: '/certs/ca.pem'
    # volumes:
    #   - .docker/adminer/login-ssl.php:/var/www/html/plugins-enabled/login-ssl.php
    #   - ./certs/client-key.pem:/certs/client-key.pem
    #   - ./certs/client-cert.pem:/certs/client-cert.pem
    #   - ./certs/root-ca.pem:/certs/ca.pem

  node:
    image: node:17.3.0-alpine3.15
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run watch

#  console:
#    image: web
#    entrypoint: bin/console
#    volumes:
#      - ./:/var/www/html
#      #- ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
#    environment:
#      PHP_IDE_CONFIG: serverName=localhost
#      #XDEBUG_CONFIG: "remote_host=192.168.1.53"

  migration:
    image: ${REGISTRY_HOSTNAME}/${APP_NAME}-phpfpm:${APP_VERSION}
    build:
      dockerfile: Dockerfile
      context: .
      
      args:
        APP_VERSION: ${APP_VERSION}
    depends_on:
      - "db"
    volumes:
    - "./:/srv"
    # Run with php ./bin/console migration:reset for db rebuild from scartch
    command: php ./bin/console migration:continue
    environment:
      NETTE_ENV: ${NETTE_ENV}
      APP_VERSION: ${APP_VERSION}

  assets:
    image: ${REGISTRY_HOSTNAME}/${APP_NAME}-assets:${APP_VERSION}
    build:
      dockerfile: Dockerfile.assets
      context: .
    volumes:
      - "./www/assets:/usr/share/caddy/assets"

  phpfpm:
    image: ${REGISTRY_HOSTNAME}/${APP_NAME}-phpfpm:${APP_VERSION}
    build:
      dockerfile: Dockerfile
      context: .
      args:
        APP_VERSION: ${APP_VERSION}
    depends_on:
      - "db"
      - "migration"
      - "redis"
    ports:
      - 9000
    volumes:
    - "./:/srv"
    environment:
      NETTE_ENV: ${NETTE_ENV}

  nginx:
    image: nginx:1.21.5-alpine
    depends_on:
    - "phpfpm"
    - "assets"
    ports:
      - '8080:80'
    volumes:
        - ".docker/nginx/site.conf:/etc/nginx/conf.d/default.conf"

#   minio:
#     image: docker.io/bitnami/minio:2022.1.8-debian-10-r14
#     ports:
#       - '9001:9001'
#     volumes:
#       - 'minio_data:/data'
#     environment:
#       MINIO_DEFAULT_BUCKETS: data
#       MINIO_ROOT_USER: minio
#       MINIO_ROOT_PASSWORD: minio123

# volumes:
#   minio_data:
#     driver: local
