FROM composer:2.1.12 as BUILDER

COPY ./config /app/config
COPY ./composer.json /app/
COPY ./composer.lock /app/

RUN cd /app && composer install --ignore-platform-reqs

FROM node:17.3.0-alpine3.15 as BUILDER-NODE

COPY ./webpack.config.js /app/
COPY ./package.json /app/
COPY ./package-lock.json /app/
COPY ./frontend /app/frontend
COPY --from=BUILDER /app/vendor /app/vendor

RUN cd /app && npm run build

FROM caddy:2.4.6-alpine

COPY --from=BUILDER-NODE /app/www/assets /usr/share/caddy/assets
